s3_bucket: models-resources
s3_key_prefix: geniventure-dashboard
s3_endpoint: us-east-1
gzip: true

cloudfront_distribution_id: E3UJ5EG44XIXTH
cloudfront_invalidate_root: true
cloudfront_wildcard_invalidation: true

<% if ENV['TRAVIS_BRANCH'] == 'production' %>
# in this case we are going to deploy this branch to the top level of the domain
# so we need to ignore the version and branch folders
ignore_on_server: ^geniventure-dashboard/(version/|branch/)
<% else %>
# in this case we are going to deploy this code to a subfolder of either the branch
# or version folder. So ignore everything except this folder.
# S3_DEPLOY_DIR is set by s3_deploy.sh
ignore_on_server: ^(?!geniventure-dashboard/<%= Regexp.escape(ENV['S3_DEPLOY_DIR']) %>/)
<% end %>
max_age:
  "geniventure-dashboard/*": 600 # 10 minutes
  "geniventure-dashboard/version/*": 31536000 # 1 year
  "geniventure-dashboard/branch/*": 0

cloudfront_distribution_config:
  aliases:
    quantity: 1
    items:
      - geniventure-dashboard.concord.org
